<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	# Current controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>

		<!-- Main -->
			<div id="main">
				<div class="inner">

					<!-- title -->
						<h1><?php echo $title ?></h1>
						<div class="golden-separator"></div>

					<!-- Result -->
					<section id="result" class="result">
						<!-- abstract -->
							<?php if (!empty($abstract)) { ?>
							<div class="line-tittle-wrap">
								<div class="info_value"><?php echo $abstract ?></div>
								<div id="authorship_text"></div>
							</div>
							<?php }//if (!empty($abstract)) ?>

						<!-- body -->
							<?php if (!empty($body)) { ?>
							<div id="row_body">
								<div class="block-expandable" id="block_expandable">
									<div id="body_text" class="info_text_block hide_opacity"><?php echo $body ?></div>
								</div>
							</div>
							<?php }//if (!empty($body)) ?>

						<!-- Form -->
							<section class="form">
								<?php #include($cwd.'_search.phtml') ?>
								<div id="items_container"></div>
							</section>

						<!-- Charts -->
							<div id="regression_model_section" class="hide">
								<div class="info_line separator"><div class="big_label"><?php echo tstring('regression_model')?></div></div>
								<div id="regression_model_chart_container" class="chart_wrapper"></div>
							</div>

					</section>
				</div>
			</div>

		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
dom_ready(function(){
	var regression = regression_min.regression
	regression.set_up({
		row									: <?php echo json_encode($this->row) ?>,
		area_name							: <?php echo json_encode($area_name) ?>,
		export_data_container				: document.getElementById('export_data'),
		form_items_container				: document.getElementById('items_container'),
		regression_model_chart_container	: document.getElementById('regression_model_chart_container')
	})
	// active expandable block
	const block_expandable = document.getElementById('block_expandable')
	const row_body = document.getElementById('row_body')
	const body_text = document.getElementById('body_text')
	if (block_expandable && row_body) {
		page.create_expandable_block(
			block_expandable,
			row_body
		)
		body_text.classList.remove('hide_opacity')
	}
})
</script>