<?php
# REQUIRED FILES
	$base_path	= dirname(dirname(__FILE__));
	$cwd		= basename($base_path); # Current dir name

	// Current controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>


		<!-- Main -->
			<div id="main">
				<div class="inner">

					<!-- title -->
						<h1><?php echo $title ?></h1>
						<div class="golden-separator"></div>

					<section class="result">
						<!-- abstract -->
							<?php if (!empty($abstract)) { ?>
							<div class="line-tittle-wrap">
								<div class="info_value"><?php echo $abstract ?></div>
							</div>
							<?php }//if (!empty($abstract)) ?>

						<!-- body -->
							<?php if (!empty($body)) { ?>
							<div id="row_body">
								<div class="block-expandable" id="block_expandable">
									<div class="info_text_block"><?php echo $body ?></div>
								</div>
							</div>
							<?php }//if (!empty($body)) ?>
					</section>

					<!-- Form -->
						<section class="form">
							<div id="items_container"></div>
							<div id="view_options"></div>
						</section>

					<!-- Result -->
						<section class="result">
							<div id="rows_list"></div>
						</section>

				</article>
				</div>
			</div>


		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
dom_ready(function(){
	thesaurus.set_up({
		table		: <?php echo json_encode($thesaurus_options->table) ?>,
		root_term	: <?php echo json_encode($thesaurus_options->root_term) ?>,
		term_id		: <?php echo json_encode($thesaurus_options->term_id) ?>,
		ar_fields	: <?php echo json_encode($thesaurus_options->ar_fields) ?>,
		rows_list	: document.getElementById('rows_list')
	})
	// active expandable block
	const block_expandable = document.getElementById('block_expandable')
	const row_body = document.getElementById('row_body')
	if (block_expandable && row_body) {
		page.create_expandable_block(
			block_expandable,
			row_body
		)
	}
})
</script>
