<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	// Current controller add
	require($base_path .'/'. $cwd .'.php');
?>

<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>


		<!-- Main -->
			<div id="main">
				<div class="inner">

					<!-- title -->
						<h1 class="no_print"><?php echo $title ?></h1>
						<div class="golden-separator no_print"></div>

					<!-- Form -->
						<div id="form_container" class="form_container no_print"></div>

					<!-- Result -->
						<section id="rows_container" class="result no_print"></section>

					<!-- biblio_print -->
						<div id="biblio_print" class="biblio_print"></div>

					<!-- export_data -->
					<div id="export_data" class="export_data_container no_print">
						<div class="export_container">
							<input class="btn primary button_print hidden" type="button" value="<?php echo tstring('print') .' '. tstring('bibliographic_references') ?>">
						</div>
					</div>
				</div>
			</div>


		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
dom_ready(function(){
	mints.set_up({
		form_container	: document.getElementById('form_container'),
		rows_container	: document.getElementById('rows_container')
	})
})
</script>
